name: Run JMeter Performance Tests

on:
  workflow_dispatch:
    inputs:
      usersNumber:
        default: 5
        type: number
        description: Number of users to run in parallel
      duration:
        description: Duration of the test
        default: 600
        type: number

jobs:
  jmeter-test:
    timeout-minutes: 1450
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '16'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.9.6'

      - name: Run JMeter Tests with Maven
        run: mvn clean verify -Djmeter.testfile="SDK Finance Performance Test.jmx" -DusersNumber=5 -Dduration=1200
        continue-on-error: true

      - name: Upload JMeter report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: target/jmeter/
